FROM python:latest

#WORKDIR /home/app
#COPY . .

#RUN python3 -m pip install -r /home/app/requirements.txt
RUN python3 -m pip install requests==2.27.1 && \
    python3 -m pip install pandas==1.4.1 && \
    python3 -m pip install beautifulsoup4